id: A51B6555A
title: Prayer to Shechen Kongtrul as Vajrasattva
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:30:03.283136
  last_modified_at: 2022-03-01 00:30:03.283139
