id: A51B6555A
title: Clouds of Offerings to Delight the Victorious Ones – An Aspiration Prayer for
  the Spread of the Teachings of the Lord of Siddhas, Dzogchen Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:30:03.280923
  last_modified_at: 2022-03-01 00:30:03.280931
